import type { AuditReport, ComparisonReport } from '../domain/models.js';

export function formatMarkdownReport(report: AuditReport): string {
  const lines: string[] = [];
  const meta = report.metadata;
  const health = report.healthScore;
  const bus = report.busFactor;
  const act = report.activity;

  lines.push(
    `# 🔍 RepoVet Audit: [${report.repo.owner}/${report.repo.name}](https://github.com/${report.repo.owner}/${report.repo.name})`
  );
  lines.push('');
  if (meta.description) {
    lines.push(`> *${meta.description}*`);
    lines.push('');
  }

  // Summary Table
  lines.push('## 📊 Executive Summary');
  lines.push('');
  lines.push('| Indicator | Value | Rating / Details |');
  lines.push('| :--- | :---: | :--- |');
  lines.push(
    `| **Overall Health Grade** | **${health.grade}** | \`${health.compositeScore}/100\` composite score |`
  );
  lines.push(`| **Hygiene Standards** | \`${health.hygieneScore}/100\` | 40% weight |`);
  lines.push(
    `| **Maintenance & Velocity** | \`${health.activityScore}/100\` | ${act.isStale ? '⚠️ STALE' : '✅ ACTIVE'} (${act.commitsLast30Days} commits in last 30d) |`
  );
  lines.push(
    `| **Bus Factor** | **${bus.busFactor}** | ${bus.risk.toUpperCase()} risk (Gini: \`${bus.giniCoefficient.toFixed(2)}\`, ${bus.totalContributors} contributors) |`
  );
  lines.push(
    `| **Stars / Forks** | ★ ${meta.stars.toLocaleString()} / ⑂ ${meta.forks.toLocaleString()} | Open Issues: ${meta.openIssues.toLocaleString()} |`
  );
  lines.push(
    `| **License** | \`${meta.license ?? 'None'}\` | Default Branch: \`${meta.defaultBranch}\` |`
  );
  lines.push('');

  // Tech Stack & Languages
  lines.push('## ⚙️ Tech Stack & Languages');
  lines.push('');
  if (report.languages.length > 0) {
    const langRows = report.languages.map((l) => `\`${l.name}\` (${l.percentage}%)`).join(' · ');
    lines.push(`**Languages:** ${langRows}`);
    lines.push('');
  }

  const stack = report.stack;
  lines.push('| Category | Detected Technologies |');
  lines.push('| :--- | :--- |');
  lines.push(
    `| **Runtimes** | ${stack.runtimes.length > 0 ? stack.runtimes.join(', ') : 'None detected'} |`
  );
  lines.push(`| **Package Manager** | ${stack.packageManager ?? 'None detected'} |`);
  lines.push(
    `| **Frameworks** | ${stack.frameworks.length > 0 ? stack.frameworks.join(', ') : 'None detected'} |`
  );
  lines.push(
    `| **Tooling & Build** | ${stack.buildTools.length > 0 ? stack.buildTools.join(', ') : 'None detected'} |`
  );
  lines.push(`| **Containers** | ${stack.hasDocker ? 'Docker' : 'None'} |`);
  lines.push(
    `| **CI/CD** | ${stack.ciWorkflows.length > 0 ? stack.ciWorkflows.join(', ') : 'None'} |`
  );
  lines.push('');

  // Hygiene Checklist Table
  lines.push('## 🛡️ Hygiene Standards Checklist');
  lines.push('');
  lines.push('| Status | Check Item | Weight | Importance |');
  lines.push('| :---: | :--- | :---: | :---: |');
  for (const item of report.hygiene.checks) {
    const status = item.found ? '✅ PASS' : '❌ FAIL';
    lines.push(`| ${status} | **${item.name}** | ${item.weight} pts | ${item.importance} |`);
  }
  lines.push('');

  // Recommendations
  const missing = report.hygiene.checks.filter((c) => !c.found);
  if (missing.length > 0) {
    lines.push('### ⚡ Actionable Recommendations');
    lines.push('');
    for (const item of missing) {
      lines.push(`* [ ] **Add ${item.name}:** ${item.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    `*Generated by [RepoVet](https://github.com/jeremi-code/repo-audit) v${report.version} on ${new Date(report.timestamp).toUTCString()}*`
  );
  lines.push('');

  return lines.join('\n');
}

export function formatMarkdownComparisonReport(comparison: ComparisonReport): string {
  const lines: string[] = [];
  const reports = comparison.reports;

  lines.push('# ⚔️ RepoVet: Repository Comparison Battle Mode');
  lines.push('');

  // Comparison Table
  const headers = [
    'Metric / Indicator',
    ...reports.map(
      (r) => `[${r.repo.owner}/${r.repo.name}](https://github.com/${r.repo.owner}/${r.repo.name})`
    ),
  ];
  const separator = [':---', ...reports.map(() => ':---:')];

  lines.push(`| ${headers.join(' | ')} |`);
  lines.push(`| ${separator.join(' | ')} |`);

  lines.push(
    `| **Health Grade** | ${reports.map((r) => `**${r.healthScore.grade}** (\`${r.healthScore.compositeScore}/100\`)`).join(' | ')} |`
  );
  lines.push(
    `| **Hygiene Score** | ${reports.map((r) => `\`${r.hygiene.score}/100\``).join(' | ')} |`
  );
  lines.push(
    `| **Activity Status** | ${reports.map((r) => (r.activity.isStale ? '⚠️ STALE' : '✅ ACTIVE')).join(' | ')} |`
  );
  lines.push(
    `| **Last Push** | ${reports.map((r) => (r.activity.lastPushedDaysAgo === 0 ? 'Today' : `${r.activity.lastPushedDaysAgo}d ago`)).join(' | ')} |`
  );
  lines.push(
    `| **Commits (30d)** | ${reports.map((r) => r.activity.commitsLast30Days.toLocaleString()).join(' | ')} |`
  );
  lines.push(
    `| **Commits (90d)** | ${reports.map((r) => r.activity.commitsLast90Days.toLocaleString()).join(' | ')} |`
  );
  lines.push(
    `| **Bus Factor** | ${reports.map((r) => `**${r.busFactor.busFactor}** (${r.busFactor.risk})`).join(' | ')} |`
  );
  lines.push(
    `| **Gini Inequality** | ${reports.map((r) => `\`${r.busFactor.giniCoefficient.toFixed(2)}\``).join(' | ')} |`
  );
  lines.push(
    `| **Stars** | ${reports.map((r) => `★ ${r.metadata.stars.toLocaleString()}`).join(' | ')} |`
  );
  lines.push(
    `| **Forks** | ${reports.map((r) => `⑂ ${r.metadata.forks.toLocaleString()}`).join(' | ')} |`
  );
  lines.push(
    `| **License** | ${reports.map((r) => `\`${r.metadata.license ?? 'None'}\``).join(' | ')} |`
  );
  lines.push(
    `| **Primary Language** | ${reports.map((r) => r.languages[0]?.name ?? 'Unknown').join(' | ')} |`
  );
  lines.push(
    `| **Frameworks** | ${reports.map((r) => (r.stack.frameworks.length > 0 ? r.stack.frameworks.slice(0, 2).join(', ') : 'None')).join(' | ')} |`
  );
  lines.push('');

  // Winner section
  if (comparison.winner) {
    const w = comparison.winner;
    lines.push(
      `### 🏆 Top Pick: [${w.repo.owner}/${w.repo.name}](https://github.com/${w.repo.owner}/${w.repo.name})`
    );
    lines.push(`* **Score:** \`${w.score}/100\` (Grade **${w.grade}**)`);
    lines.push('* **Key Advantages:**');
    for (const reason of w.reasons) {
      lines.push(`  * ${reason}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    `*Generated by [RepoVet](https://github.com/jeremi-code/repo-audit) v${comparison.version} on ${new Date(comparison.timestamp).toUTCString()}*`
  );
  lines.push('');

  return lines.join('\n');
}
