import { describe, expect, it } from 'vitest';
import type { AuditReport, ComparisonReport } from '../../src/domain/models.js';
import {
  formatMarkdownComparisonReport,
  formatMarkdownReport,
} from '../../src/formatters/markdown.formatter.js';

const mockReportA: AuditReport = {
  version: '1.3.0',
  repo: { owner: 'facebook', name: 'react' },
  timestamp: '2026-09-21T00:00:00.000Z',
  fromCache: false,
  metadata: {
    description: 'The library for web and native user interfaces.',
    stars: 220000,
    forks: 45000,
    openIssues: 700,
    license: 'MIT',
    defaultBranch: 'main',
    isArchived: false,
    isFork: false,
    createdAt: '2013-05-24T00:00:00Z',
    updatedAt: '2026-09-21T00:00:00Z',
    pushedAt: '2026-09-21T00:00:00Z',
  },
  hygiene: {
    score: 95,
    grade: 'A+',
    checks: [
      {
        id: 'license',
        name: 'License',
        description: 'Permissive open source license',
        importance: 'critical',
        found: true,
        weight: 25,
      },
      {
        id: 'contributing',
        name: 'Contributing Guide',
        description: 'Contributing instructions',
        importance: 'recommended',
        found: false,
        weight: 15,
      },
    ],
  },
  languages: [
    { name: 'JavaScript', bytes: 80000, percentage: 80 },
    { name: 'TypeScript', bytes: 20000, percentage: 20 },
  ],
  stack: {
    runtimes: ['Node.js'],
    packageManager: 'yarn',
    frameworks: ['React'],
    buildTools: ['Rollup'],
    hasDocker: false,
    ciWorkflows: ['runtime.yml'],
  },
  busFactor: {
    busFactor: 8,
    giniCoefficient: 0.42,
    risk: 'healthy',
    totalContributors: 1500,
    topContributors: [{ login: 'gaearon', commits: 500, percentage: 10 }],
  },
  activity: {
    lastPushedDaysAgo: 0,
    commitsLast30Days: 85,
    commitsLast90Days: 240,
    isStale: false,
  },
  healthScore: {
    compositeScore: 92,
    grade: 'A',
    hygieneScore: 95,
    activityScore: 96,
    busFactorScore: 88,
  },
};

const mockReportB: AuditReport = {
  version: '1.3.0',
  repo: { owner: 'vuejs', name: 'core' },
  timestamp: '2026-09-21T00:00:00.000Z',
  fromCache: false,
  metadata: {
    description: 'Vue.js core repository',
    stars: 45000,
    forks: 8000,
    openIssues: 200,
    license: 'MIT',
    defaultBranch: 'main',
    isArchived: false,
    isFork: false,
    createdAt: '2018-09-01T00:00:00Z',
    updatedAt: '2026-09-20T00:00:00Z',
    pushedAt: '2026-09-20T00:00:00Z',
  },
  hygiene: {
    score: 85,
    grade: 'A',
    checks: [
      {
        id: 'license',
        name: 'License',
        description: 'Permissive open source license',
        importance: 'critical',
        found: true,
        weight: 25,
      },
    ],
  },
  languages: [{ name: 'TypeScript', bytes: 100000, percentage: 100 }],
  stack: {
    runtimes: ['Node.js'],
    packageManager: 'pnpm',
    frameworks: ['Vue'],
    buildTools: ['Vite'],
    hasDocker: false,
    ciWorkflows: ['ci.yml'],
  },
  busFactor: {
    busFactor: 3,
    giniCoefficient: 0.65,
    risk: 'moderate',
    totalContributors: 300,
    topContributors: [{ login: 'yyx990803', commits: 1200, percentage: 45 }],
  },
  activity: {
    lastPushedDaysAgo: 1,
    commitsLast30Days: 40,
    commitsLast90Days: 110,
    isStale: false,
  },
  healthScore: {
    compositeScore: 84,
    grade: 'B',
    hygieneScore: 85,
    activityScore: 90,
    busFactorScore: 75,
  },
};

describe('MarkdownFormatter', () => {
  it('formats single repository audit report in GitHub Flavored Markdown', () => {
    const md = formatMarkdownReport(mockReportA);

    expect(md).toContain('# 🔍 RepoVet Audit: [facebook/react](https://github.com/facebook/react)');
    expect(md).toContain('The library for web and native user interfaces.');
    expect(md).toContain('| **Overall Health Grade** | **A** | `92/100` composite score |');
    expect(md).toContain('## 🛡️ Hygiene Standards Checklist');
    expect(md).toContain('### ⚡ Actionable Recommendations');
    expect(md).toContain('* [ ] **Add Contributing Guide:** Contributing instructions');
    expect(md).toContain(
      '*Generated by [RepoVet](https://github.com/jeremi-code/repo-audit) v1.3.0'
    );
  });

  it('formats multi-repository comparison battle mode report', () => {
    const comparison: ComparisonReport = {
      version: '1.3.0',
      timestamp: '2026-09-21T00:00:00.000Z',
      reports: [mockReportA, mockReportB],
      winner: {
        repo: mockReportA.repo,
        score: 92,
        grade: 'A',
        reasons: ['Higher overall composite score (92/100 vs 84/100)'],
      },
    };

    const md = formatMarkdownComparisonReport(comparison);

    expect(md).toContain('# ⚔️ RepoVet: Repository Comparison Battle Mode');
    expect(md).toContain('[facebook/react](https://github.com/facebook/react)');
    expect(md).toContain('[vuejs/core](https://github.com/vuejs/core)');
    expect(md).toContain('### 🏆 Top Pick: [facebook/react](https://github.com/facebook/react)');
    expect(md).toContain('Higher overall composite score (92/100 vs 84/100)');
  });
});
